//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteMeta2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidades : DbContext
    {
        public Entidades()
            : base("name=Entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_acao> tb_acao { get; set; }
        public virtual DbSet<tb_coluna> tb_coluna { get; set; }
        public virtual DbSet<tb_dependencia> tb_dependencia { get; set; }
        public virtual DbSet<tb_perfil> tb_perfil { get; set; }
        public virtual DbSet<tb_perfil_acao> tb_perfil_acao { get; set; }
        public virtual DbSet<tb_relacao> tb_relacao { get; set; }
        public virtual DbSet<tb_tipodado> tb_tipodado { get; set; }
        public virtual DbSet<tb_usuario> tb_usuario { get; set; }
        public virtual DbSet<tb_tabela_acao> tb_tabela_acao { get; set; }
        public virtual DbSet<tb_tabela> tb_tabela { get; set; }
    }
}
