//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteMeta2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_coluna
    {
        public int col_codigo { get; set; }
        public int tb_codigo { get; set; }
        public string col_nome { get; set; }
        public string col_titulo { get; set; }
        public int td_codigo { get; set; }
        public int col_tamanho { get; set; }
        public bool col_podevazio { get; set; }
        public bool col_primarykey { get; set; }
        public bool col_visivel { get; set; }
        public bool col_filtrar_coluna { get; set; }
        public string tb_tabela { get; set; }
        public Nullable<int> col_ordem { get; set; }
        public Nullable<bool> col_visivel_tablet { get; set; }
        public string col_filtro_lista { get; set; }
        public Nullable<bool> col_alteravel_inclusao { get; set; }
        public Nullable<bool> col_visivel_inclusao { get; set; }
        public string col_padrao { get; set; }
        public Nullable<bool> dm_ordenavel { get; set; }
        public string col_mascara { get; set; }
        public Nullable<int> nr_qtd_dias_anterior { get; set; }
        public Nullable<int> nr_qtd_dias_frente { get; set; }
        public Nullable<bool> dm_virtual { get; set; }
        public Nullable<bool> dm_pode_foto { get; set; }
        public string midia_mime_type { get; set; }
        public Nullable<int> cd_usuario_inc { get; set; }
        public Nullable<bool> dm_situacao { get; set; }
        public Nullable<System.DateTime> dt_inclusao { get; set; }
        public Nullable<bool> col_podevazio_tablet { get; set; }
        public Nullable<bool> dm_obrigatorio_impressao { get; set; }
        public Nullable<bool> col_visivel_alteracao { get; set; }
        public Nullable<bool> dm_uppercase { get; set; }
        public Nullable<bool> col_visivel_detalhe { get; set; }
        public Nullable<bool> col_marca_dagua { get; set; }
        public Nullable<int> cd_marca_dagua { get; set; }
        public Nullable<bool> col_subpasta { get; set; }
        public string col_diretorio { get; set; }
        public Nullable<bool> col_alteravel_alteracao { get; set; }
        public Nullable<bool> col_ordenacao_padrao { get; set; }
        public Nullable<bool> col_ordenacao_crescente { get; set; }
        public string col_filtro_registros { get; set; }
    }
}
