//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteMeta2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_dependencia
    {
        public int dep_codigo { get; set; }
        public string col_nome { get; set; }
        public string dep_nome { get; set; }
        public string dep_valor { get; set; }
        public Nullable<int> tb_codigo { get; set; }
        public Nullable<int> cd_usuario_inc { get; set; }
        public Nullable<bool> dm_situacao { get; set; }
        public Nullable<System.DateTime> dt_inclusao { get; set; }
    }
}
