//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteMeta2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_tabela
    {
        public int tb_codigo { get; set; }
        public string tb_nome { get; set; }
        public string tb_titulo { get; set; }
        public bool tb_gerenciador { get; set; }
        public bool tb_menu { get; set; }
        public bool tb_selecionar { get; set; }
        public Nullable<bool> dm_situacao { get; set; }
        public string nm_coluna_calculada { get; set; }
        public Nullable<int> cd_usuario_inc { get; set; }
        public Nullable<System.DateTime> dt_inclusao { get; set; }
    }
}
