//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteMeta2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        public int cd_usuario { get; set; }
        public string nm_usuario { get; set; }
        public string ds_email { get; set; }
        public string nm_login { get; set; }
        public string img_foto { get; set; }
        public string ds_senha { get; set; }
        public Nullable<int> cd_perfil { get; set; }
        public Nullable<int> cd_local { get; set; }
        public Nullable<bool> dm_situacao { get; set; }
        public Nullable<bool> dm_gestor_setor { get; set; }
        public string nr_matricula { get; set; }
        public string nr_telefone { get; set; }
        public Nullable<bool> dm_tecnico { get; set; }
        public Nullable<int> cd_usuario_inc { get; set; }
        public Nullable<System.DateTime> dt_inclusao { get; set; }
        public Nullable<int> cd_sla { get; set; }
        public Nullable<int> cd_orgao { get; set; }
        public string nm_cargo { get; set; }
        public Nullable<bool> dm_ativo { get; set; }
    }
}
